name: "test"
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "src-tauri/**"
  pull_request:
    paths:
      - "src-tauri/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  rust-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v5

      - uses: swatinem/rust-cache@v2
        with:
          workspaces: "./src-tauri -> target"

      - name: Run Rust tests
        working-directory: src-tauri
        run: cargo test
